# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prototype
  labels:
    app: prototype
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prototype
  template:
    metadata:
      labels:
        app: prototype
    spec:
      containers:
        - name: prototype
          image: <REGISTRY>/<NAMESPACE>/myapp:v1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: CLOUDANT_URL
              valueFrom:
                secretKeyRef:
                  name: cloudant
                  key: url
                  optional: true
